var picture = `MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWX0kdollllodk0NWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOo;''',:ccc:;,'.';oONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNx,.'lx0NWWMMMMMWX0xc,.,o0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK:.,xXWMMMMMMMMMMMWWMMNOc..oXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNc ;KMWMMMMMMMMMMMMWWMMMMW0;.;0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMx.'OMMMMMMMMMMMMMMMMMMMMMMMXl.;KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWl :NMMMMMMMMMMMMMMMMMMMMMMMMK, oWMMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNc cNMMMMMMMMMMMMMMMMMMMMMMMMN: .oKWMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWo ;XMMMMMMMMMMMMMMMMMMMMMMMMO'.:,'dNMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO..xWMMMMMMMMMMMMMMMMMMMMMMXc cN0' cXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWd.'OWMMMMMMMMMMMMMMMMMMMMNl.;KMWc  cXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNo..lddooodxOKNWMMWWMMMMWd.,0MMNc  .xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMMMMMMMMMWd..;ccc:;;,,;:lkKWMMMM0''0WMM0'   cNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKo;l0MMMMMMMMK;.co::lxkkkxdc;,,:xKWWo.dMMWNl    :NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXd;,,.lWMMWKodd;:o,    .lkkkkkkkdc,,lO:,0MWNd.    cWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0dlll;;k0x,;XMNd;,..oNd      ,xkkkkkkkkxo;'.'0WXo.    .kMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNXXWN00KNMMMMMMMMMMMMMMMMMXo.  ...dKOd,.co:;O0,.kWk.    ;x0Kkoccloxkkko'.lk;      cNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKl;;;;'.'';lxkOO0000000OOOOk:    .::;;;;,::..kWX: .oOklccoONWW0;    .,lxkl.        ;KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWk'.lk: .dkxd:,,,,,;;;;;;,,,'''.... ,k00OOOkxo;:c;.   :XW0l'.;0WX:       :d'.;.     ;KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0l.'k0d' oK;cNWNNNNNNNNNNNNNNNNNX0kl.'kXWWWWNKOdc'..   lWO'    lWNl       cd':kd'  .cXWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMNk:.'oKW0:. lKo:kXXXXXNNNNWWNNNNNNNNX0o.,kXWNXKOl;'':o,  '0MOld: .xWMXd,...,dXNOxdc..:kNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOo,.;xXWNKkl, .co::,....''',;:ccldxkkOOO:.:k0Oo:;'':xOkc.  .xNNNWOlkNN0xl::lx0XNXd;;lxKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMWKxc'.;oOKkl;'',;,,;:;,;coxkkxxdolc:,.....';;..oxc'..,o0NW0d' :: 'loKKKNKOOx:..,...';;,dXWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMWXOdl;..;oO0x:'.;lx0XNNNWMWWMMMMMMMMMMMMM0,        :xd:..'ckXWKko.'OOd;..:,;l,;:,':dd,  .oKXNX0OOXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMNkc..':lxKNKl'.:xKWWMMMMMMMMMMMMMMMMMMMMMMNc        'dxOOd;'.'okxdd:.oNW0xk:,c'.;ccdkd,.:' .::cc:..OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMWKd;. 'kNMMMXd'.lKWWMMMMMMMMMMMMMMMMMMMMMMMMMk.       .odONW0xdo..;loxd'.dNWWWXNMX0Kkdl:'.cko. :OKKo'oWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMWMMMWMWNkc,'.  oWMWN0;.:0WMMMMMMMMMMMMMMMMMMMMMMMMMMMWl       .lxONWKd:,'':oxxxo...;lxO0kdl:'.  .:oxOk; 'xOc.oNMMWNX0XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMW0o;,;;:l, .o00d'.oNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK,      'ok0NXk;..,cdxdddxl.'c'..',. ...  .oxxx0Ko. ';'.;ddc;;'.dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMNx;,:lccoxoo:.....'xNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMx.    .;dOXWNOdc..',,....'. .;..okx; ,oc..oxxxxKNO,.:xxc..:oxk;,0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMWd.:dlcdOdckk:lx, .xWMMMMMMWMMMMMMMMMMMMMMMMMMMMMMMX; ...,lkKWWWWKd;.  ..',,,'. .'.:kkc.,;..;dxlodkXW0:.,dxd,.dNWd'xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMWM0'.,cxOdcdKk;dKc:x,;KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNl 'oddk0NMMMN0:...,,;cllccllc' .lkc..:;,lx0Ko,:xOxd:.'dxxd:';:.cNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMd  .od:dXNx:xXo.,Kk':KMMMMMMMMMMMMMMMMMMMMMMMMMMMWd..lxxx0WMMWXd' .;;'.;l:..clllc' ',...'cdOXWNO;......':dxxxxdl;.'dXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMWc    .lNKlc0No;:.lNO,;0MMMMMMMMMMMMMMMMMMMMMMMMMNd. :ddxxk0WWKo. ,c,.'cc'  .cllll,  .':lxOKWMMWKc.   .cxxxdlc;,'.. .kMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMX:   'c:;,oXNo,xNd':l'.lWMMMWWMMMMMMMMMMMMMMMMMMWx. ;ddloxxxOOl. ,c. .,,.   ,lllll; .:xxxxOO000K0l.'ollol:,;;::.    lNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMWX:  ;KM0;':c;;kWWWx.'xo,lKWMWWMMMMMMMMMMMMMMMMMMMK; ,dxc;oocdo. ,:.  ..    .;lllll:. ';,........'..;xl;..,xKX0x,  .oNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMWNc 'OWK:c0O;'OWWMMWO:cdd,,OWMMMMMMMMMMMMMMMMMMMMMMO. ,dd''l;.. 'c.         .:lc:llc.        ..'',,,;'    ,0MWKkc .dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMWk;:l:c';KWx;kWWWMMMMNOolloKMMMMMMMMMMMMMMMMMMMMMWO;.. 'ol..c' .c'          .cl,'clc.    .':lodxxd:.       ,KMXOo..xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMXl:kNO, .;cc:kWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKl..:o;..lc.  .:,           .cc..coc.  .;oxxdoddc.    .'cx; lNWKk; ;KWWXK0OO0KNWMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMWk;c0Ol,.;Kk';0WMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0;  .;:l;..cc..;;            .l; .cll'  .''..':dl. .':d0NMMO'.OMXOo. ,:,.......';lONMMMMMMMMMMMMMMMMMMMMM
MMMMWx.;lloc':OxcdNMMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk.      .. .'.':.            'c. .:oo;.    .;lo;,ckKNMMWMMMNc lWW0x;  .,,;;,,;:;'..:0WMMMMMMMMMMMMMMMMMMM
MMMMW0dxkKK;.cldKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWM0'           .:.             ,:. .:lo;. .',;,'..xWMMMWX0koc;. ,KMN0d' .,...  'lllc. ,OMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMNkdkXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWNo          .:,              ;;. .:ll:.    ..''c0KOdl;..      '0MWXOo.      .clccl:. oWMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWNN0,        .;:.              ,'  .;llc. .,;,..,:,..           cXKkoldd,    'cc,.;lc. lWMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNKkoc;,''.        .;.              .,.  .,lll' .'.                  .xKdc'..;:. .;c,. .:o:..xMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOl,..';codxxxxxdol:,'.                '.   'lll;                      .c:';lo:.   .;.   ;ll, .OMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKo'.'cdOKXXKKKK0KKKKXXXKOxoc,.           .     ....                         lNMWK;.;.     'llc. ;XMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXo..:k0K0OOkkkkkkkkkkkkkkOO0KKKOxl,.                                          lNMMXool.    .cc:;. oWMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0,.;kK0OkkOOOkkkkkkkkkkOOOOkkkkkO0KKOdc..            .,:ldxOOOOxl,.          ''.dWWKkx,    .:;.,; .kMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0'.l0OOOkkkkOOOkkOkkkkkkkkkkkOkkdocccdOKOkxc.    .;lxOXWWNKOxolc::;.     .':dON0,,KWKk:    .,' .:, '0MMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMX:.cOOOOkkkkkOOkkkkkkkOkkkOkdl:,..... .'cxkO0Ox:. .oKWNOocccclodddol:.  'dONWMMMNc.kWKd.    ..  'c' :NMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk..xOkkOkkkkkkkkkkkkOOOOko;'....,;:;::'. ':okk0K0d;..:ccdkKNNXKOkdolc;. oMMMMMMMWc.xN0l.       .:l. lWMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMo ,kOkkOkkkkkkkkkkxocccl:. ';:llllc..;c:.  .okkkO0KOl..;kXXX0Oxolllol, .OMMMMMMMWc.xNO;        'lc. dMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWd 'xOkkkkkkkkkkkkd'..,'.  'llloxOx:.  .cc.  .oOOkkO0K0d;.':cclllol:,'.'kWWMMMMMMN:.ONk'       .:lc..kMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO. :kkkkOOkkkOOkl..lKWNd. 'x0XNWW0c.   ,l;.. ;kkkkOkkO0KOl.    .,c,.,dXMMMMMMMMMK;'0Nx.       ,:::..OMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNd..;ooc:,'.,:l;..dNMWWk. .oXMMMMXd;.  ,l:,. 'xOkkOkkOkk0K0d,    'lkNMMMMMMMMMMMk.:XXd.      .:.,:..OMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXk;  ....',,.   ,kNWXkc'.  'kX0kxdolc,',c;'. ,kOkkOOOkkOkkO00x:. ;kXMMMMMMMMMMMWl.oNKx'     .;. ':..OMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0;  .',:clc;:, .lKXkc,,:dx:  'llllllc:;'..  .,dOkkkkkkkkkkkkkkOKOl'.,dKWMMMMN0xoc' '::c.     ',  ,;..OMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNc .:lllloo,. .:kOdlcokOxc,... .,;,'.....,:looxOOkkkkkkOOkkkkkkOkOK0x;..cxxoc::ll:''....     .,.  ';..OMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK; 'oxxk0Kx, ,ON0Okkxl,'.,:lddc'...';codkOkkkkkkkkkkkkkkkkkkkkkOOkkO0Kkc.  .l0Xx:;c:;;,;'    ..   '; .kWMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMX; .kNWMWW0c..d0xl,.  ;dkkOOOOkkxdxkOOkkOOkkkkkkkkkkkkkkkkkkOOkkkkkkkOO00d,..:;,cc;::':c.    .    ..  ;llcllodxOKWMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWo .lXMWNXOd:....,;. .lOkkkOOOkkOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOOOOOkkOOkO00c..cl;;l:'cc.                        .,lONMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK; .oOxdollll:,;;'.  ,ldkkkkOkkOOOkkkkkkOkkkkkkkkkkkkkkkkkkkOOkkkkkOkkOxlc,.;;'cd;.lc.                  ..',;;:::,.;0WMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0; .,cllc:,'....';oo;..':oxOkkkOkkkkkkkkkkkkkkkkkkkkkkkkkkkkOkkOOkOxl:;co:...;l,,o:.             .,coxO0XNWWNNXXKk,'OMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXo' ......,cdkKNWMMWKxc'..,cdkOOOkkkkkkkkkkkkkkkkkkkkkkkkOkkOkkOkl;;ll:;:od;..,l;          .'cdOXWWX0kdlc:clloodx: lWMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXkdlox0XWMMMMMMMWWMMWNOo;..':oxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOkc,c:;:ldl;;:c,.. .::.   .:d0NWKkoc;,;:cc::oxOKNWXl'xWMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKxc'..,cdkOkkkkkkkOOOkkkkkkkkkkkOkkOx;'..co;,,,;'..';cdO0Oo'..oOkl;,,,,,cdkO0KXXNNKkl:cOWMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOo;..':oxkOOkkOOkOOkkkkkkkkkOOOOkko,....';,;coxkOkkOkO00x:.   .codxxkkOKNNKOxc::lONMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWKxc'..,:cdkOOkOOkkkkkkkOOOkkOOkkkoccldkOOOOkkkkkOOOkk0Kkl. .:lxO00Odol:;;cd0NMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOo;'..':lxkkkkkkkkkkOOOkkkkkkOOOOOOOkkOOOkkkkOOkxoc:cc;'..';,;;:cdk0NMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNKxc'..,cdkOkkkkkOOOOOOkkkkOOkkOOOOkOOkkkdc;'...''..',,.  .';;;;;c0MWMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNOo;..';lxkOOkkkOOkkkkkkkkkOkOOkkkko,..';:cl:';c,.'oxxdo:,.  ,OMMWMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMMMMMWKxc'..,cdkkOkkkkkkkkkkOOkd:,;,'..;ooxk0x,  .:; .coc;..,ckXMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMMMMMMMMMWNOo;...;lxkOOOOkkkOOkl.,x0O; .oKXWWW0:.  'l'  .;lx0NMMWMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKxc'..'cll;'.,:l:.cXMMWo  cXMWWWKd,  'l;. lWMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXk;.  ..'',.  .oNWKx:.. .dKOkdoll:',:,  dWMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXc..',:clc,,..;OKx:;:odl. .:lolc:;,'...'lXMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMx..coodkO: .;xOkodxxdc,.';...'....,cok0NWMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMo 'xKXNWNo.,KNOxdc,';lx0NWKxlclxOXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMx..xWMWMW0:.,:,'. .dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMX: ,OXOkxdl:,';:' 'OWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0, 'clllc:;'....;kNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKl.......,:lxOXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWKxoldOKNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM`

console.log(picture);
